// Angular InstantSearch/debounced-search-box/src/app/debounced-search-box.component.ts
import { Component, Inject, forwardRef, Input } from "@angular/core";
import { BaseWidget, NgAisInstantSearch } from "angular-instantsearch";
import { connectSearchBox } from "instantsearch.js/es/connectors";

@Component({
  selector: "app-debounced-search-box",
  template: `
    <input
      class="ais-SearchBox"
      type="text"
      #input
      (keyup)="onChangeDebounced(input.value)"
      [value]="this.state.query"
    />
  `
})
export class DebouncedSearchBox extends BaseWidget {
  private timerId = null;
  state: {
    query: string;
    refine: Function;
  };

  @Input() delay: number = 0;

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super("DebouncedSearchBox");
  }

  public onChangeDebounced(value) {
    if (this.timerId) clearTimeout(this.timerId);
    this.timerId = setTimeout(() => this.state.refine(value), this.delay);
  }

  public ngOnInit() {
    this.createWidget(connectSearchBox, {});
    super.ngOnInit();
  }
}

// Vue InstantSearch/debounced-search-box/src/components/DebouncedSearchBox.vue
<template>
  <input type="search" v-model="query" class="ais-SearchBox-input" />
</template>

<script>
import { connectSearchBox } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from 'vue-instantsearch';

export default {
  mixins: [createWidgetMixin({ connector: connectSearchBox })],
  props: {
    delay: {
      type: Number,
      default: 200,
      required: false,
    },
  },
  data() {
    return {
      timerId: null,
      localQuery: '',
    };
  },
  destroyed() {
    if (this.timerId) {
      clearTimeout(this.timerId);
    }
  },
  computed: {
    query: {
      get() {
        return this.localQuery;
      },
      set(val) {
        this.localQuery = val;
        if (this.timerId) {
          clearTimeout(this.timerId);
        }
        this.timerId = setTimeout(() => {
          this.state.refine(this.localQuery);
        }, this.delay);
      },
    },
  },
};
</script>
