// react-instantsearch/range-slider-with-radix-ui/src/App.js
import {
  Hits,
  InstantSearch,
  Pagination,
  RefinementList,
  SearchBox,
} from 'react-instantsearch';
import algoliasearch from 'algoliasearch/lite';

import { RangeSlider } from './RangeSlider';

import './App.css';

const searchClient = algoliasearch(
  'B1G2GM9NG0',
  'aadef574be1f9252bb48d4ea09b5cfe5'
);

function App() {
  return (
    <div className="container">
      <InstantSearch
        searchClient={searchClient}
        indexName="demo_ecommerce"
        insights={true}
      >
        <div className="search-panel">
          <div className="search-panel__filters">
            <RefinementList attribute="brand" />
            <RangeSlider attribute="price" />
          </div>

          <div className="search-panel__results">
            <SearchBox className="searchbox" placeholder="Search" />
            <Hits />

            <div className="pagination">
              <Pagination />
            </div>
          </div>
        </div>
      </InstantSearch>
    </div>
  );
}

export default App;

// Angular InstantSearch/getting-started/src/app/app.component.ts
import { Component } from '@angular/core';
import * as algoliasearch from 'algoliasearch/lite';

const searchClient = algoliasearch(
  'B1G2GM9NG0',
  'aadef574be1f9252bb48d4ea09b5cfe5'
);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  config = {
    indexName: 'demo_ecommerce',
    searchClient
  };
}

<div class="ais-InstantSearch">
  <h1>Angular InstantSearch e-commerce demo</h1>
  <ais-instantsearch [config]="config">
    <div class="left-panel">
      <ais-current-refinements></ais-current-refinements>
      <h2>Brands</h2>
      <ais-refinement-list attribute="brand"></ais-refinement-list>
      <ais-configure [searchParameters]="{ hitsPerPage: 8 }"></ais-configure>
    </div>
    <div class="right-panel">
      <ais-search-box></ais-search-box>
      <ais-hits>
        <ng-template let-hits="hits">
          <ol class="ais-Hits-list">
            <li *ngFor="let hit of hits" class="ais-Hits-item">
              <img src="{{hit.image}}" alt="{{hit.name}}" align="left" />
              <div class="hit-name">
                <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
              </div>
              <div class="hit-description">
                <ais-highlight attribute="description" [hit]="hit"></ais-highlight>
              </div>
              <div class="hit-price">${{hit.price}}</div>
            </li>
          </ol>
        </ng-template>
      </ais-hits>
      <ais-pagination></ais-pagination>
    </div>
  </ais-instantsearch>
</div>
