// Angular InstantSearch/query-suggestions/src/app/app.component.ts
import { Component } from '@angular/core';
import * as algoliasearch from 'algoliasearch';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public configSuggestions = {
    indexName: 'instant_search_demo_query_suggestions',
    searchClient,
  };
  public configResults = {
    indexName: 'instant_search',
    searchClient,
  };

  public searchParameters = { query: '' };

  setQuery(query : string) {
    this.searchParameters.query = query
  }
}

<header class="header">
  <h1 class="header-title">
    <a href="/">query-suggestions</a>
  </h1>
  <p class="header-subtitle">
    using
    <a href="https://github.com/algolia/angular-instantsearch">
      Angular InstantSearch
    </a>
  </p>
</header>

<div class="container">
  <ais-instantsearch [config]="configSuggestions">
    <ais-configure [searchParameters]="{hitsPerPage: 3}"></ais-configure>
    <div class="search-box">
      <app-autocomplete (onQuerySuggestionClick)="setQuery($event)"></app-autocomplete>
    </div>
  </ais-instantsearch>

  <ais-instantsearch [config]="configResults">
    <ais-configure [searchParameters]="searchParameters"></ais-configure>
    <div class="search-panel">
      <div class="search-panel__results">
        <ais-hits>
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>

            <ol class="ais-Hits-list">
              <li class="ais-Hits-item" *ngFor="let hit of hits">
                <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
              </li>
            </ol>
          </ng-template>
        </ais-hits>
      </div>
    </div>
  </ais-instantsearch>
</div>

// react-instantsearch/multi-index-hits/src/App.jsx
import algoliasearch from 'algoliasearch/lite';
import {
  Configure,
  Highlight,
  Hits,
  Index,
  InstantSearch,
  SearchBox,
} from 'react-instantsearch';

import 'instantsearch.css/themes/algolia.css';
import './App.css';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

function App() {
  return (
    <div className="container">
      <InstantSearch
        indexName="instant_search"
        searchClient={searchClient}
        insights={true}
      >
        <SearchBox />

        <Index indexName="instant_search">
          <h2>
            index: <code>instant_search</code>
          </h2>
          <Configure hitsPerPage={16} />
          <Hits hitComponent={ProductHit} />
        </Index>

        <Index indexName="instant_search_demo_query_suggestions">
          <h2>
            index: <code>instant_search_demo_query_suggestions</code>
          </h2>
          <Configure hitsPerPage={8} />
          <Hits hitComponent={QuerySuggestionHit} />
        </Index>
      </InstantSearch>
    </div>
  );
}

function ProductHit({ hit }) {
  return (
    <div>
      <Highlight attribute="name" hit={hit} />
    </div>
  );
}

function QuerySuggestionHit({ hit }) {
  return (
    <div>
      <Highlight attribute="query" hit={hit} />
    </div>
  );
}

export default App;
