// Angular InstantSearch/loading-indicator/src/app/loading-indicator.component.ts
import { Component, Inject, forwardRef, OnInit } from "@angular/core";
import { BaseWidget, NgAisInstantSearch } from "angular-instantsearch";

const connectSearchMetaData = (renderFn, unmountFn) => (widgetParams = {}) => ({
  init() {
    renderFn({ searchMetadata: {} }, true);
  },
  render({ searchMetadata }) {
    renderFn({ searchMetadata }, false);
  },
  dispose() {
    unmountFn();
  }
});

@Component({
  selector: "app-loading-indicator",
  template: `
    <div>
      <div *ngIf="state.searchMetadata && state.searchMetadata.isSearchStalled">
        Loading...
      </div>
    </div>
  `
})
export class LoadingIndicator extends BaseWidget implements OnInit {
  state: {
    searchMetadata: object;
  };

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super("LoadingIndicator");
  }

  public ngOnInit() {
    this.createWidget(connectSearchMetaData as any, {});
    super.ngOnInit();
  }
}

// Vue InstantSearch/loading-indicator/src/components/LoadingIndicator.vue
<template>
  <div v-if="state && state.searchMetadata.isSearchStalled">
    <slot> <p>Loading…</p> </slot>
  </div>
</template>

<script>
import { createWidgetMixin } from 'vue-instantsearch';

const connectSearchMetaData = (
  renderFn,
  unmountFn
) => (/* widget has no parameters */) => ({
  init() {
    renderFn({ searchMetadata: {} }, true);
  },

  render({ searchMetadata }) {
    renderFn({ searchMetadata }, false);
  },

  dispose() {
    unmountFn();
  },
});

export default {
  name: 'AisStateResults',
  mixins: [createWidgetMixin({ connector: connectSearchMetaData })],
};
</script>
