// onboarding/demos/react/geo/src/Hit.tsx
import React from 'react'
import { Highlight } from 'react-instantsearch-hooks-web'
import type { Hit as BaseHit } from 'instantsearch.js'

import { Airport } from './Airports'

type HitProps = {
  hit: BaseHit<Airport>
}

export function Hit({ hit }: HitProps) {
  return (
    <div className="hit">
      <h2 className="hit-name">
        <span className="hit-airport-name">
          <Highlight attribute="name" hit={hit} />{' '}
          <Highlight attribute="city" hit={hit} />{' '}
        </span>
        <span className="hit-airport-code">
          (<Highlight attribute="airport_id" hit={hit} />)
        </span>
      </h2>
      <p className="hit-location">
        <Highlight attribute="country" hit={hit} /> <br />
        <span className="hit-distance">
          {hit._rankingInfo && hit._rankingInfo.matchedGeoLocation && (
            <span>
              {Math.round(hit._rankingInfo.matchedGeoLocation.distance / 1000)}
              km away,{' '}
            </span>
          )}
          {hit.nb_airline_liaisons} connections
        </span>
      </p>
    </div>
  )
}

// onboarding/demos/vue/geo/src/components/Hit.vue
<template>
  <div class="hit">
    <h2 class="hit-name">
      <span class="hit-airport-name">
        <ais-highlight attribute-name="name" :result="result"/>
        <ais-highlight attribute-name="city" :result="result"/>
      </span>
      <span class="hit-airport-code">
        (<ais-highlight attribute-name="airport_id" :result="result"/>)
      </span>
    </h2>
    
    <p class="hit-location">
      <ais-highlight attribute-name="country" :result="result"/><br>
      <span class="hit-distance">
        <span v-if="result._rankingInfo && result._rankingInfo.matchedGeoLocation">
          {{ getFormattedDistance(result._rankingInfo.matchedGeoLocation.distance) }} km away,
        </span> {{ result.nb_airline_liaisons }} liaisons
      </span>
    </p>
  </div>
</template>

<script>
export default {
  props: {
    result: Object
  },
  methods: {
    getFormattedDistance(distance) {
      return parseInt(distance / 1000, 10)
    }
  }
}
</script>
