// Angular InstantSearch/routing-basic/src/app/app.component.ts
import { Component } from '@angular/core';
import algoliasearch from 'algoliasearch/lite';

const searchClient = algoliasearch(
  'B1G2GM9NG0',
  'aadef574be1f9252bb48d4ea09b5cfe5'
);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  config = {
    indexName: 'demo_ecommerce',
    searchClient,
    routing: true,
  };
}

<header class="header">
  <h1 class="header-title">
    <a href="/">routing-basic</a>
  </h1>
  <p class="header-subtitle">
    using
    <a href="https://github.com/algolia/angular-instantsearch">
      Angular InstantSearch
    </a>
  </p>
</header>

<div class="container">
  <ais-instantsearch [config]="config">
    <div class="search-panel">
      <div class="search-panel__filters">
        <h3>Brands</h3>
        <ais-refinement-list attribute="brand"></ais-refinement-list>
      </div>
      <div class="search-panel__results">
        <div class="searchbox">
          <ais-search-box placeholder=""></ais-search-box>
        </div>

        <ais-hits>
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>

            <ol class="ais-Hits-list">
              <li class="ais-Hits-item" *ngFor="let hit of hits">
                <article>
                  <h1>
                    <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
                  </h1>

                  <p>
                    <ais-highlight
                      attribute="description"
                      [hit]="hit"
                    ></ais-highlight>
                  </p>
                </article>
              </li>
            </ol>
          </ng-template>
        </ais-hits>

        <div class="pagination">
          <ais-pagination></ais-pagination>
        </div>
      </div>
    </div>
  </ais-instantsearch>
</div>

// Vue InstantSearch/routing-basic/src/App.vue
<template>
  <div>
    <header class="header">
      <h1 class="header-title">
        <a href="/">Basic URLs</a>
      </h1>
      <p class="header-subtitle">
        using
        <a href="https://github.com/algolia/vue-instantsearch">Vue InstantSearch</a>
      </p>
    </header>

    <div class="container">
      <ais-instant-search
        :search-client="searchClient"
        index-name="demo_ecommerce"
        :routing="routing"
      >
        <div class="search-panel">
          <div class="search-panel__filters">
            <ais-clear-refinements/>

            <ais-panel>
              <template slot="header">Category</template>

              <ais-menu attribute="categories"/>
            </ais-panel>

            <ais-panel>
              <template slot="header">Brands</template>

              <ais-refinement-list attribute="brand"/>
            </ais-panel>
          </div>

          <div class="search-panel__results">
            <ais-search-box placeholder="Search here…" class="searchbox"/>
            <ais-hits>
              <template slot="item" slot-scope="{ item }">
                <h1>
                  <ais-highlight :hit="item" attribute="name"/>
                </h1>
                <p>
                  <ais-highlight :hit="item" attribute="description"/>
                </p>
              </template>
            </ais-hits>

            <div class="pagination">
              <ais-pagination/>
            </div>
          </div>
        </div>
      </ais-instant-search>
    </div>
  </div>
</template>

<script>
import algoliasearch from 'algoliasearch/lite';
import { history as historyRouter } from 'instantsearch.js/es/lib/routers';
import { simple as stateMapping } from 'instantsearch.js/es/lib/stateMappings';
import 'instantsearch.css/themes/algolia-min.css';

export default {
  data() {
    return {
      searchClient: algoliasearch(
        'B1G2GM9NG0',
        'aadef574be1f9252bb48d4ea09b5cfe5'
      ),
      routing: {
        router: historyRouter(),
        stateMapping: stateMapping(),
      },
    };
  },
};
</script>

<style>
body,
h1 {
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
}

.ais-Highlight-highlighted {
  background: cyan;
  font-style: normal;
}

.header {
  display: flex;
  align-items: center;
  min-height: 50px;
  padding: 0.5rem 1rem;
  background-image: linear-gradient(to right, #4dba87, #2f9088);
  color: #fff;
  margin-bottom: 1rem;
}

.header a {
  color: #fff;
  text-decoration: none;
}

.header-title {
  font-size: 1.2rem;
  font-weight: normal;
}

.header-title::after {
  content: ' ▸ ';
  padding: 0 0.5rem;
}

.header-subtitle {
  font-size: 1.2rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 1rem;
}

.search-panel {
  display: flex;
}

.search-panel__filters {
  flex: 1;
  margin-right: 1em;
}

.search-panel__filters > div {
  margin-bottom: 2rem;
}

.search-panel__results {
  flex: 3;
}

.searchbox {
  margin-bottom: 2rem;
}

.pagination {
  margin: 2rem auto;
  text-align: center;
}
</style>
