// onboarding/demos/angular/saas/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  config = {
    appId: "B1G2GM9NG0",
    apiKey: "aadef574be1f9252bb48d4ea09b5cfe5",
    indexName: "demo_saas",
    searchParameters: {
      hitsPerPage: 4,
      distinct: 3
    }
  };

  groupByType(items: Object[]) {
    const newItems = {};
    items.forEach((item: { type }) => {
      if (!newItems[item.type]) {
        newItems[item.type] = [item];
      } else {
        newItems[item.type].push(item);
      }
    });
    newItems["isEmpty"] = Object.keys(newItems).length === 0;
    return newItems;
  }
}

<ais-instantsearch [config]="config">
  <main class="search-container">
    <div class="right-panel">
      <div id="hits">
        <!-- Uncomment the following widget to add hits list -->
        <!-- <ais-hits [transformItems]="groupByType">
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.isEmpty">
              No results found for
              <strong>{{results.query}}</strong>.
            </div>
            <div class="hit" *ngIf="hits['Contact']">
              <h2>Contacts</h2>
              <div class="table-responsive">
                <table>
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th>Account</th>
                      <th>Email</th>
                    </tr>
                    <tr *ngFor="let hit of hits['Contact']">
                      <td>
                        <ais-highlight attribute="Name" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Account" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Email" [hit]="hit">
                        </ais-highlight>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="hit" *ngIf="hits['Opportunity']">
              <h2>Opportunities</h2>
              <div class="table-responsive">
                <table>
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th>Account</th>
                      <th>Owner</th>
                      <th>CloseDate</th>
                      <th>StageName</th>
                      <th>Amount</th>
                    </tr>
                    <tr *ngFor="let hit of hits['Opportunity']">
                      <td>
                        <ais-highlight attribute="Name" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Account" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Owner" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="CloseDate" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="StageName" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        {{hit.Amount}}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="hit" *ngIf="hits['Account']">
              <h2>Accounts</h2>
              <div class="table-responsive">
                <table>
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th>Website</th>
                      <th>Owner</th>
                    </tr>
                    <tr *ngFor="let hit of hits['Account']">
                      <td>
                        <ais-highlight attribute="Name" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Website" [hit]="hit" *ngIf="hit.Website">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Owner" [hit]="hit">
                        </ais-highlight>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="hit" *ngIf="hits['Lead']">
              <h2>Leads</h2>
              <div class="table-responsive">
                <table>
                  <tbody>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Owner</th>
                    </tr>
                    <tr *ngFor="let hit of hits['Lead']">
                      <td>
                        <ais-highlight attribute="Name" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Email" [hit]="hit">
                        </ais-highlight>
                      </td>
                      <td>
                        <ais-highlight attribute="Owner" [hit]="hit">
                        </ais-highlight>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </ng-template>
        </ais-hits> -->
      </div>
      <div id="searchbox">
        <!-- Uncomment the following widget to add a search bar -->
        <!-- <ais-search-box placeholder="Search in your CRM"></ais-search-box> -->
      </div>
      <div id="stats">
        <!-- Uncomment the following widget to add search stats -->
        <!-- <ais-stats>
          <ng-template let-state="state">
            <div *ngIf="state.nbHits> 0">
              <span role="img" aria-label="emoji">⚡️</span>
              <strong>{{state.nbHits}}</strong>
              results found
              <span *ngIf="state.query.trim().length > 0">
                for
                <strong>"{{state.query.trim()}}"</strong>
              </span>
              in
              <strong>{{state.processingTimeMS}}ms</strong>
            </div>
          </ng-template>
        </ais-stats> -->
      </div>
    </div>
    <div class="left-panel">
      <div id="type">
        <!-- Uncomment the following widget to add types list -->
        <!-- <ais-panel header="Categories">
          <ais-refinement-list attribute="type">
          </ais-refinement-list>
        </ais-panel> -->
      </div>
    </div>
  </main>
</ais-instantsearch>
<footer>
  Source Code on
  <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
  <a href="https://www.algolia.com">Algolia</a>
</footer>

// onboarding/demos/vue/media/src/App.vue
<template>
  <ais-index
    app-id="B1G2GM9NG0"
    api-key="aadef574be1f9252bb48d4ea09b5cfe5"
    index-name="demo_media"
    :query-parameters="{
      hitsPerPage: 3,
      attributesToSnippet: ['content:14'],
      snippetEllipsisText: ' [...]'
    }"
  >
    <main class="search-container">
      <div class="right-panel">
        <div id="hits">
          <!-- Uncomment the following widget to add hits list -->
          <!-- <ais-results class="ais-hits">
            <div slot-scope="{ result }">
              <hit :result="result"/>
            </div>
          </ais-results>
          <ais-no-results>
            <div slot-scope="props">
              No results found for <strong>{{ props.query }}</strong>.
            </div>
          </ais-no-results> -->
        </div>
        <div id="searchbox">
          <!-- Uncomment the following widget to add a search bar  -->
          <!-- <ais-search-box placeholder="Search articles" class="ais-search-box"/> -->
        </div>
        <div id="stats">
          <!-- Uncomment the following widget to add search stats -->
          <!-- <div>
            <ais-stats>
              <div slot-scope="{ totalResults, processingTime, query, resultStart, resultEnd }">
                <span role="img" aria-label="emoji">⚡️</span> <strong>{{ totalResults }}</strong> results found
                <span v-if="query !== ''">for <strong>"{{ query }}"</strong></span>
                in <strong>{{ processingTime }}ms</strong>
              </div>
            </ais-stats>
          </div> -->
        </div>
        <div id="pagination">
          <!-- Uncomment the following widget to add pagination -->
          <!-- <ais-pagination>
            <span slot="first">«</span>
            <span slot="previous">‹</span>
            <span slot="next">›</span>
            <span slot="last">»</span>
          </ais-pagination> -->
        </div>
      </div>
      <div class="left-panel">
        <div id="categories">
          <!-- Uncomment the following widget to add categories list -->
          <!-- <refinement-list attribute-name="categories" header-title="Categories"/> -->
        </div>
      </div>
    </main>
    <footer>
      Source Code on
      <a href="https://github.com/algolia/doc-onboarding">GitHub</a> | Powered by
      <a href="https://www.algolia.com">Algolia</a>
    </footer>
  </ais-index>
</template>

<script>
import Hit from './components/Hit'
import RefinementList from './components/RefinementList'

export default {
  components: {
    Hit,
    RefinementList
  }
}
</script>

<style src="./assets/styles.css"></style>
