// Vue InstantSearch/refresh/src/components/Refresh.vue
<template>
  <button @click="refresh">refresh</button>
</template>

<script>
import { createWidgetMixin } from 'vue-instantsearch';

const connectRefresh = (
  renderFn,
  unmountFn
) => (/* this widget has no parameters */) => ({
  init() {
    renderFn({ refresh: () => {} }, true);
  },

  render({ instantSearchInstance }) {
    const refresh = instantSearchInstance.refresh.bind(instantSearchInstance);
    renderFn({ refresh }, false);
  },

  dispose() {
    unmountFn();
  },
});

export default {
  mixins: [createWidgetMixin({ connector: connectRefresh })],
  methods: {
    refresh() {
      this.state.refresh();
    },
  },
};
</script>

// Angular InstantSearch/refresh/src/app/refresh.component.ts
import { Component, Inject, forwardRef, OnInit } from "@angular/core";
import { BaseWidget, NgAisInstantSearch } from "angular-instantsearch";

const connectRefresh = (renderFn, unmountFn) => (widgetParams = {}) => ({
  init() {
    renderFn({ refresh() {} }, true);
  },
  render({ instantSearchInstance }) {
    const refresh = instantSearchInstance.refresh.bind(instantSearchInstance);
    renderFn({ refresh }, false);
  },
  dispose() {
    unmountFn();
  }
});

@Component({
  selector: "app-refresh",
  template: `
    <button (click)="state.refresh()">Refresh</button>
  `
})
export class Refresh extends BaseWidget implements OnInit {
  state: {
    refresh: Function;
  };

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super("Refresh");
  }

  public ngOnInit() {
    this.createWidget(connectRefresh as any, {});
    super.ngOnInit();
  }
}
